### ISSUE TITLE
how to genrate json from master detail table 

### ISSUE THREAD

**Issue by ADITYASOFTWARE** [pljson/pljson#113]
We have Master table BILL , child Table BILL_DETAIL  how can I get below output in PL/JSON 
{
       "billLists":[{
               "docType":"INV",
               "docNo":"67876",
               "docDate":"03/03/2017",
               "fromTrdName":"AMBUJA LTD",
               "fromAddr1":"KG ROAD",
               "fromAddr2":"KG ROAD",
              "totalValue":678,
               "cgstValue":0,
               "sgstValue":0,
               "igstValue":678,
               "transMode":1,
               "vehicleNo":"KA12KA1234",
                         "itemList":[{
                                "itemNo":1,
                                "productName":"STEEL",
                                "productDesc":"STEEL",
                                "hsnCode":26180000,
                                "quantity":567,
                                "qtyUnit":"KGS",
                                "taxableAmount":678,
                                "sgstRate":0,
                                "cgstRate":9,
                                "igstRate":0
                              }

                              ]
}

**Comment by dsnz** [comment]
Hello,

It is very easy. Just write your select (joining master and detail the way you like) and use json_dyn.executeList().
I copy below an example use from example 16 (ex16.sql).

```
set serveroutput on;
declare 
  ret json_list;
begin
  ret := json_dyn.executeList('select * from tab');
  ret.print;
end;
```

**Comment by ADITYASOFTWARE** [comment]
Dear sir
           Thank you for your ans. We try, But we are get below result.

SQL> declare
  2    ret json_list;
  3  begin
  4    ret := json_dyn.executeList('select
decode("SAL_INV"."SNO",1,"SALES"."INV
_NO")INV_NO,
  5      decode("SAL_INV"."SNO",1,"SALES"."DOC_DT",null) as "DOC_DT",
  6      "SAL_INV"."SNO" as "SNO",
  7      "SAL_INV"."ITEM_CD" as "ITEM_CD",
  8      "SAL_INV"."QTY" as "QTY",
  9      "SAL_INV"."RATE" as "RATE",
 10      "SAL_INV"."NET_AMT" as "NET_AMT"
 11   from       PER."SAL_INV" "SAL_INV",
 12      PER."SALES" "SALES"
 13   where   "SALES"."SDOC_NO"="SAL_INV"."SDOC_NO"
 14    and       "SALES"."SDOC_NO" = 1821
 15    order by "SAL_INV"."SNO"');
 16    ret.print;
 17  end;
 18  /


[{
"INV_NO" : "4",
"DOC_DT" : "2017-08-11 00:00:00",
"SNO" : 1,
"ITEM_CD" : 61,
"QTY" : 1,
"RATE" : 50000,
"NET_AMT" : 50000
}, {
"INV_NO" : "",
"DOC_DT" : "",
"SNO" : 2,
"ITEM_CD" : 82,
"QTY" : 14,
"RATE" : 5000,
"NET_AMT" : 70000
}, {
"INV_NO" : "",
"DOC_DT" : "",
"SNO" : 3,
"ITEM_CD" : 82,
"QTY" : 0.01,
"RATE" : 164.05,
"NET_AMT" : 820.25
}, {
"INV_NO" : "",
"DOC_DT" : "",
"SNO" : 4,
"ITEM_CD" : 82,
"QTY" : 0.02,
"RATE" : 5000,
"NET_AMT" : 100
}, {
"INV_NO" : "",
"DOC_DT" : "",
"SNO" : 5,
"ITEM_CD" : 82,
"QTY" : 0.5,
"RATE" : 5000,
"NET_AMT" : 2500
}, {
"INV_NO" : "",
"DOC_DT" : "",
"SNO" : 6,
"ITEM_CD" : 82,
"QTY" : 0.03,
"RATE" : 1640.5,
"NET_AMT" : 0
}]
PL/SQL procedure successfully completed.


We are looking for output like below where inv_no,doc_dt not  return again

[{
"INV_NO" : "4",
"DOC_DT" : "2017-08-11 00:00:00",
"SNO" : 1,
"ITEM_CD" : 61,
"QTY" : 1,
"RATE" : 50000,
"NET_AMT" : 50000
}, {
"SNO" : 2,
"ITEM_CD" : 82,
"QTY" : 14,
"RATE" : 5000,
"NET_AMT" : 70000
}, {
"SNO" : 3,
"ITEM_CD" : 82,
"QTY" : 0.01,
"RATE" : 164.05,
"NET_AMT" : 820.25
}, {
"SNO" : 4,
"ITEM_CD" : 82,
"QTY" : 0.02,
"RATE" : 5000,
"NET_AMT" : 100
}, {
"SNO" : 5,
"ITEM_CD" : 82,
"QTY" : 0.5,
"RATE" : 5000,
"NET_AMT" : 2500
}, {
"SNO" : 6,
"ITEM_CD" : 82,
"QTY" : 0.03,
"RATE" : 1640.5,
"NET_AMT" : 0
}]

**Comment by dsnz** [comment]
Hi,

Your requirement is strange, and I'd say not orthogonal since you want a list of objects where the first object is a bit different than the rest (has a few extra fields). May I suggest some other options ?

1. Leave the result as it is and in case you need to parse the JSON then simply ignore null values for INV_NO,DOC_DT or ignore the fields INV_NO,DOC_DT when SNO is greater than 1. Another option is to avoid the 'decode' in the sql and output all master data for all rows. This will add a bit to the JSON size (trivial really) but is still correct information and again you can parse result JSON easily and get separately the master and detail data.
Really in practice, it is not worth the complexity in having different object output for first and rest elements in list (it makes it less understandable when read by a human, also increases associated complexity of parsing program and documentation, ...)

2. Use an alternate JSON format like the following

{
"master": {
"INV_NO" : "4",
"DOC_DT" : "2017-08-11 00:00:00"
},
"detail": [{
"SNO" : 1,
"ITEM_CD" : 61,
"QTY" : 1,
"RATE" : 50000,
"NET_AMT" : 50000
}, ...]
}

This is a better option and is essentially a separation of master and detail data.

3. Change the code so that null values are not output. I just mention this as a bad option and I DO NOT recommend it since in your development of other applications you may have null values that will not appear in JSON but you need them to appear. Also, the correct behavior is to output all requested fields whatever value they have (that's why there is 'null' in Oracle).

Consider the above and you decide how you prefer to proceed. Feel free to ask any further assistance.

**Comment by ADITYASOFTWARE** [comment]
Sir Thank you. Please give us documents,Examples if any , How to construct
Sql and Pl/sql in pl/json.

**Comment by dsnz** [comment]
Hi,

You can study all examples in `examples` folder.
I close this as you have no specific issue any more.
