### ISSUE TITLE
12c support

### ISSUE THREAD

**Issue by Tagar** [pljson/pljson#12]
Great project. Does it support 12c? 12.1 has native support for JSON.
I'm looking something like json_dyn() that is implemented here, but could not find 
analogue implemented directly in 12.1.
Thanks!

**Comment by jsumners** [comment]
I don't have access to 12c. You could try it and report your findings. That would be most helpful.

**Comment by epint** [comment]
Hello I'm evaluating pl/json too. We are looking for a library that would work across different versions of database (10g, 11g, 12c and on). I found out that on 12c there could be issue (or at least confusion) with json_value type. The name json_value is also used by Oracle SQL function.  Haven't tested everything but PL/JSON seem to work on 12c.

Any chance for type renaming (maybe with optional synonym for backward compatibility)? 

Otherwise, native JSON support in 12c looks pretty limited (parsing only?).

**Comment by jsumners** [comment]
Again, I don't have access to 12c. I wouldn't be able to test such a mechanism if I wrote it. I'd welcome a pull request, though.

**Comment by OscarValdez** [comment]
What is the lowest version of oracle  that the library can handle? - I have 9

**Comment by jsumners** [comment]
I think the biggest requirement would be support for the ANYDATA type. A
quick search tells me that 9i has such support. But if you can successfully
install it, maybe in a test scheme, and report back, I'd be sure to note
the result.

On Thursday, September 10, 2015, OscarValdez <notifications@github.com>
wrote:

> What is the lowest version of oracle that the library can handle? - I have
> 9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pljson/pljson/issues/12#issuecomment-139396858>.
>


-- 
James Sumners
http://james.sumners.info/ (technical profile)
http://jrfom.com/ (personal site)
http://haplo.bandcamp.com/ (band page)

**Comment by dsnz** [comment]
PL/JSON works perfectly on 10g and 11g. On 12c it needs some simple modifications which I am planning to introduce in near future. On 9i PL/JSON does not compile for

```
JSON_TABLE     because of missing functionality in 9i,
JSON_UTIL_PKG  because of a string literal in new format intriduced after 9i,
JSON_PARSER    because of missing REGEXP_LIKE()
JSON_EXT       because of missing REGEXP_LIKE()
```

also a few other packages/types call the above at certain places

the net result is that PL/JSON can be used mainly to create new json documents
and convert them to text representation but not the opposite
(for example 'json_unicode_test.sql' does run on 9i)

however the modifications needed so it compiles fine on 9i are easy to do
(for example 90% of the calls to REGEXP_LIKE() are there to test for strict compliance
to json format if using the 'strict' option, these could be just commented out)

**Comment by jsumners** [comment]
9i support would be nice, but that is a different bug than this one.

**Comment by jsumners** [comment]
12c support is currently in the 'develop' branch and will be released with version 2.0.0 soon.

**Comment by jenniferzhang3** [comment]
Does the new version of pl/json for oracle 12.2c available now?

Which version of pl/json is working with Oracle 12.2c now?
thanks

**Comment by dsnz** [comment]
Hi,

PL/JSON should work with any Oracle version now
I have checked the release notes of 12.2c and I see no new feature that would interfere with PL/JSON operation (as far as is evident from reading release notes ...)

I do not intend to upgrade my db from 12.1 to 12.2 currently as it is much work to do this
(and I have dual installation with 11.2 which is tricky already ...)

I feel confident (😄 ) that pl/json will work without problem so I invite you to install it (the latest release) and work with it and if you are kind enough report back here if all is ok or if you spotted something

**Comment by jenniferzhang3** [comment]
Great, thanks dsnz,  I will give it try and let you know if there is any issue on this.
We are having a pljson version 1.0.4. How much changes involved for our application?
Is there any migration documents that we can use?
Thanks again

**Comment by dsnz** [comment]
1.0.4 !!!

the new pl/json is a lot different of course
old code should work (backwards compatibility is a must), but
a ton of bugs have been slain 😄 
it's faster (and will get a lot faster soon if Oracle fixes some bugs)
and new very useful features have been introduced
(some are similar to 12c json features)

there is no migration document but I suggest

1. read the README.md
2. read the example sql code in ```examples``` folder
3. take note that in latest release (since 2.0) all types and packages have been renamed from
json_xxx to pljson_xxx to avoild conflicts with Oracle 12c new keywords
for backward compatibility there are synonyms with old names pointing to the news names
these synonyms do not guarantee of course that everything will work in 12c
so in your case I suggest that you do the rename

**Comment by geridmiguel** [comment]
How install PlJson in oracle 12 and i have to change because i use plJson in oracle 11 in this moment

**Comment by dsnz** [comment]
@geridmiguel 
as you read in thread, just install it !
