### ISSUE TITLE
& issue in the pljson_util_pkg.ref_cursor_to_json(

### ISSUE THREAD

**Issue by abdul-pcfc** [pljson/pljson#135]
Hi 
When I am running this I am getting the 
LPX-00242: invalid use of ampersand ('&') character (use &amp;)
ORA-06512: at "ABDUL.PLJSON_UTIL_PKG", line 307
ORA-06512: at line 10
Is there any fix for the & character 
declare 
  ret pljson_list;
    dyn_ref sys_refcursor ;
  
  T fzexprd_dba.tb_actions;
begin
  open  dyn_ref for  select  1 ID  ,'Male &' Description from dual;
  
 ret:=pljson_util_pkg.ref_cursor_to_json(dyn_ref);
  ret.print;
end;
/

**Comment by dsnz** [comment]
Hi,

please use

```open dyn_ref for select 1 ID ,replace('Male &', '&', '&amp;') Description from dual;```

for the moment

I will see later if this is a bug

**Comment by dsnz** [comment]
Hi,

please use

```open dyn_ref for select 1 ID, replace('Male &', '&', '&amp;') Description from dual;```

for the moment

I will see later if this is a bug

**Comment by dsnz** [comment]
Hi all,

yes @boriborm is right,
the following with ```pljson_dyn.executeList``` works fine

```
declare
ret pljson_list;
dyn_s varchar2(200);
dyn_ref sys_refcursor ;

begin
dyn_s := 'select 1 ID ,''Male &'' Description from dual';

ret:=pljson_dyn.executeList(dyn_s);
ret.print;
end;
/
```
so @abdul-pcfc choose what solution you like

but I will still have to check what was the intention for proper use of ref_cursor_to_json()
and if this is a bug

**Comment by abdul-pcfc** [comment]
There is one main difference between ref_cursor and execute_list
Execute_List not bringing the values inside the cursor.
Thats y I am going for ref cursor. 
In ref cursor we can use replace query. But for me this is not practical since I have to use this in all the varchar2 fields . Kindly suggest any other option 
--ExecuteList
declare 
  ret json_list;
  dyn_query varchar2(2000);
begin
dyn_query :='select  1 ID  ,''Male'' Name ,cursor (select 10 X  from dual union select 20 from dual)A from dual';
  ret := json_dyn.executeList(dyn_query);
  ret.print;
end;
[{
  "ID" : 1,
  "NAME" : "Male"
}]

--Ref Cursor

declare 
  ret json_list;
  dyn_ref sys_refcursor ;
begin
open dyn_ref  for select  1 ID  ,'Male' Name ,cursor (select 10 X  from dual union select 20 from dual)A from dual;
  ret:=pljson_util_pkg.ref_cursor_to_json(dyn_ref);
  ret.print;
end;
/

[{
  "ID" : 1,
  "NAME" : "Male",
  "A" : [{
    "X" : 10
  }, {
    "X" : 20
  }]
}]

**Comment by dsnz** [comment]
Hi,

I guess you are trying to create a single complicated json object just from a single (and again complicated) sql statement. This is a nice idea but generally not always easy attainable in practice.

The options I can propose at this moment are:

1. use pljson_util_pkg.ref_cursor_to_json() or sql_to_json()

and escape just the varchar2 data that are necessary to escape
you need not write complex code in the select to do this
just enclose the selected data within a simple short named function
e.g. ```select x('Male &'), x(description), ... from ...;```

where x is defined as follows

```
set define off

create or replace function x(str in varchar2) return varchar2 is
/*
escape only < > &
leave as is " '

"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;

*/
begin
  return replace(replace(replace(str, '&', '&amp;'), '<', '&lt;'), '>', '&gt;');
end
```

it's a little extra coding only but it works (I have tested it)

I have also decided that there is no bug in these functions as I thought initially
a bug in the sense that these replacements should be done inside the functions (actually only sql_to_json())
BUT
we can't do the replacements in the whole sql statement (which would be very easy)
but only for specific expressions, since there may be case statements and comparisons with strings that contain '&' etc. 
however today's sql statements are very complex and not just of the simple 'select ... from ...;' variety but may include 'with' clauses, ANSI sysntax etc.
and so we should do a full sql statement parsing which is impossible practically and outside the scope of this project

2. use pljson_dyn.executeList()

with the following modifications

a. download latest repository with new features I added
(not latest release as no new release is ready yet; there will be a new release after we close this issue)

b. change your select to use multiset() and then cast to tables of strings (PLJSON_VARRAY) or numbers (PLJSON_NARRAY)
for example

```
declare
  ret pljson_list;
  dyn_query varchar2(2000);
begin
  dyn_query :='select 1 ID ,''Male'' Name ,

    cast(multiset(select ''one'' X from dual union select ''two'' from dual) as pljson_varray) A,
    cast(multiset(select 10 X from dual union select 20 from dual) as pljson_narray) B

  from dual';
  ret := json_dyn.executeList(dyn_query);
  ret.print;
end;
```
which results in
```
[{
  "ID" : 1,
  "NAME" : "Male",
  "A" : ["one", "two"],
  "B" : [10, 20]
}]
```

so as you see the new features handle columns of type PLJSON_VARRAY and PLJSON_NARRAY in the select list
it's not easy to make it generic and handle any type unfortunately
(actually it's probably impossible if we are to support Oracle 10 and upwards)

I think this covers you in most cases

If you have a more complex but real business example which cannot be handled by this
(real and not theoretical, as it is very easy to make many example cases not handled, e.g. many nested queries)
then you can post it here but we may not be able to do anything realistically and
you must use pl/sql code eventually to build the pljson object programmatically
