### ISSUE TITLE
ORA-22905 (10: 8): PL/SQL: ORA-22905: cannot access rows from a non-nested table item

### ISSUE THREAD

**Issue by daincabpu** [pljson/pljson#161]
`CREATE OR REPLACE TYPE rec_idnmb as object (
    id INTEGER,
    nombre VARCHAR2(4000)
);
/

CREATE OR REPLACE TYPE tab_idnmb as TABLE OF rec_idnmb;
/

CREATE OR REPLACE FUNCTION TESTJSON
RETURN tab_idnmb
AS
 v_ret tab_idnmb;
BEGIN
   
    select
        rec_idnmb(tmp.id,  tmp.displayname) into v_ret
    from 
       TABLE(pljson_table_impl.json_table(
      '[
        { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
        { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
        { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
      ]',
      pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
      pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
      table_mode => 'nested'
    )) ;
    
return v_ret;

END;`

When I try to create a function I get this error
ERROR [Error] ORA-22905 (10: 8): PL/SQL: ORA-22905: cannot access rows from a non-nested table item

**Comment by dsnz** [comment]
Hi,

use the following

```
CREATE OR REPLACE FUNCTION TESTJSON RETURN tab_idnmb AS
  v_ret tab_idnmb;
  v_stat varchar2(1000) :=
  'select
      rec_idnmb(tmp.id,  tmp.displayname)
  from 
     TABLE(pljson_table_impl.json_table(
    ''[
      { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
      { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
      { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
    ]'',
    pljson_varray(''[*].id'', ''[*].displayname'', ''[*].qty'', ''[*].extras[*].xid'', ''[*].extras[*].xtra''),
    pljson_varray(''id'', ''displayname'', ''qty'', ''xid'', ''xtra''),
    table_mode => ''nested''
  )) tmp;';
BEGIN
  execute immediate v_stat bulk collect into v_ret;
  return v_ret;
END;
```

see issue #58 for more information

**Comment by daincabpu** [comment]
That would force me to create a new function and a new type of data every time I want to use the library within a stored procedure or function. There is no other way to do it?

**Comment by dsnz** [comment]
You are not forced to create new functions or types !

Certainly you need not create a specialized function (like 'TESTJSON' in your example) to access the json data. You can access directly inside any of your application procedures. This is just a matter of design of your application.

The types in the code (like 'rec_idnmb' and 'tab_idnmb' in your example) are necessary because of Oracle PL/SQL type restrictions and not because of the PLJSON library.

The code workaround differs **slightly** from your original code in that it uses dynamic sql but it still uses the same flow of execution and the **same types** that were needed and that you had created in your original code. No new functions or types where created.
