### ISSUE TITLE
pljson type.get_* throwing null pointer

### ISSUE THREAD

**Issue by chambery** [pljson/pljson#184]
When calling eg. `get_number` on a valid `pljson` object with a non-existent key, I get a `ORA-30625: method dispatch on NULL SELF argument is disallowed` exception.

It seems peculiar to expect the caller to catch an NPE, and moreso when the null check code exists within the method, just commented out:

```
  member function get_number(pair_name varchar2) return number as
    elem pljson_value := get(pair_name);
  begin
    /*
    if elem is not null and elem is of (pljson_number) then
      return elem.get_number();
    end if;
    return null;
    */
    return elem.get_number();
  end;
```
https://github.com/pljson/pljson/blob/6759f4ce412eac241130d83e757969274bdc9d40/src/pljson.type.impl.sql#L279

**Comment by dsnz** [comment]
Hi,

Nice comment. In fact in issue #153 we had asked comments from users about this behavior, but there was no feedback.
The commented code was left there just in case the behavior was altered in the future (yes it's strange but we predict for the future :) or otherwise we provide code that users can uncomment at their site if they like :)).

I suggest that you use **get('pair name').get_number()** which will return null.

The whole issue is about API design.

It may seem peculiar but the proper way to handle errors is by exceptions they say :). I admit however that it makes for longer code and a null check is easier. My guess is that for most users it should be an error if a key is missing but each Oracle site has its unique needs.

Honestly at this moment, I would not like to change the code so easily unless you have a good argument of preferring one behavior over the other or if more users really find it useful. I definitely would like to hear arguments on this.
Note also that there is a workaround which results in a null value that can be checked. So, **in the current version a user has two options, either to code with exceptions or to code with null checking**. With the change you implicitly ask, only null checking will be possible.

**Comment by vlasix** [comment]
Hi @dsnz, get('pair name').get_number() does not return null. Instead it throws ORA-20005: get_number() method is not supported by object of type:null

**Comment by dsnz** [comment]
@vlasix 
Thank you for commenting. I had made a hasty mistake (I fixed it now). It's **get('pair name')** that will return null and you can check it. If the **.get_number()** is attached then it's effectively **null.get_number()** which of course throws the exception that you got.
I also re-read my whole commenting checking it further and updated it with the an extra important  argument:

"Also there is the case where the key exists but has null value and which you should be able to catch (this is impossible to catch if get_number() or get_string() return null when the key does not exist).."
