### ISSUE TITLE
Slow pljson_table.json_table operations using as a source long JSON 

### ISSUE THREAD

**Issue by kapelatp** [pljson/pljson#187]
Hi 

In fact I don't know if my file is that long (it has about 150 KB as a file on the file system).
But converting it into SQL query with takes about an hour
``
select * from table(pljson_table.json_table(
  (select  result_clob  from url_results where id = 6016),
  pljson_varray('result.requestId', 'result.subjects[*].name','result.subjects[*].nip', 'result.subjects[*].accountNumbers[*]'  ),
  pljson_varray('requestid', 'name', 'nip', 'konto' ),
  table_mode => 'nested'
));   ``

I retrived JSON with CURL.EXE and formated with JQ.EXE using windows commad line:
``
curl.exe -k -X GET "https://wl-api.mf.gov.pl/api/search/bank-account/40160014753211000000001674?date=2019-12-09" -H "accept: application/json" | jq-win32.exe  >> json.json 
``
(you can easly do the same operation - wl-api.mf.gov.pl is official open polisch service with bussiness bank accounts)

and then put JSON into table. The column RESULT_CLOB is defined as CLOB.

Are there any possibilities to make that query a little bit more "realtime"?
Are there any limitation of using pljson_table.json_table?

**Comment by dsnz** [comment]
Hi,

Is it possible that you post here or provide a link to the json text you use (the result of the command you posted) ? (just to be sure it's the exact text)

**Comment by kapelatp** [comment]
Hi

Thanks for quick response.
Here is the zip file with two example JSON's formated and raw and "mechanics" to get these files.

Tomasz Pieczykolan

[long_JSON_ex.zip](https://github.com/pljson/pljson/files/3969383/long_JSON_ex.zip)

**Comment by dsnz** [comment]
Hi,

I run a test on my 5 year old laptop with an average i3 processor, running Windows 10 and using Oracle 11 (my Oracle 12 is crashed due to bad blocks and I'm lazy to re-install it).

Runtime is:

- 673 sec or 11.2 min with latest pljson v2.0
- 500 sec or 8.3 min with latest pljson v3.0 (75% of the pljson v2.0 time)

while these are not "realtime" timings, they are much faster than 1 hour
so I suggest first that you check your installation

furthermore, nested mode is indeed slow performing as it is nested (!) and does a lot of memory manipulations of oracle collection objects
I have taken note to improve it in future (but can't promise release dates)

for your application, you can use 'cartesian' mode with the following sql

```
select *
from table(pljson_table.json_table(
(select result_clob from url_results where id = <id>),
pljson_varray('result.requestId', 'result.subjects[1].name','result.subjects[1].nip', 'result.subjects[1].accountNumbers' ),
pljson_varray('requestid', 'name', 'nip', 'konto' ),
table_mode => 'cartesian'
));
```

which produces exactly the same output and which
has a runtime for me of **5-10 sec !**

**Comment by kapelatp** [comment]
Thanks for the 'cartesian' hint. On my configuration the processing took about 45 sec which is fully acceptable.
I test it on our test server which is not in idle mode. There is some simulated random workload so as to pretend real conditions thus execution times are longer and even may differ along executions.
I'am going to run some tests tomorrow and probably use 'cartesian' mode in my application.
It would by cool to have nested mode optimized as soon as it is possible!
I'm looking forward to having it optimized.
 
Tomasz Pieczykolan

**Comment by dsnz** [comment]
It's great that there is a good workaround for your case.
I am very interested about this simulated workload you use and resulted in 5-10x slowdown. Because I don't want to pollute the issues here, I hope that you email me details about how you setup this and your test machine configuration.
Nested mode is tracking many things in order to work correctly and it suffers when the result set has many rows (3800+ in your case). It's not an issue of size of json to be parsed but an issue of total rows produced. I believe that there can be speedup with different Oracle data structures that are faster in add/update operations but I can't promise anything as I haven't reviewed the code again and as this is an open source project where we can only spend our free time on it. Certainly I will have a thorough look at what can be improved.

**Comment by kapelatp** [comment]
The mechanics of simuleted workload can't be sepereted from out system. In fact, it's "recoded" and played in loop quasi-real workload with a pinch of randomiaztion added to. It contains selecting, inserting, updating and deleting real tables in our system. Operations involeved are logistic and financial proceses - generaly boring stuff...
Almost all business logic is stucked on database so we can easyly record and playback whatever we want.
I decided to use NESTED option for smaller JSONs and CARTESIAN for bigger ones. I haven't run the tests I mentioned yet - I've had a huge amount of work this week. I have to find the "border" ctiteria of using  NESTED and CERTESIAN options.

**Comment by dsnz** [comment]
Hi,

There is a fix in v3.2.0 with 20x speed improvement (it runs now in 30 sec on my laptop and this should be compared with about 700 sec before the update, and not 500 sec as I had mentioned previously since after latest Windows 10 updates the laptop slowed considerably ... perhaps due to fixes for Intel processor vulnerabilities or just usual Windows slowdown ...).

I suggest that you move to this release. Improvements are done first for version 3 and then for version 2.

In the next 3-4 weeks I will **try (!)** to move the update to version 2 but it's not possible to do the same or similar improvements due to different object architecture and you should expect slower performance (or just a trivial improvement in the worst scenario).

**Comment by dsnz** [comment]
EDIT
after latest update on the same code on version 3.0 the similar update to version 2.0 has to be pushed ahead by 1-2 months

**Comment by jsumners** [comment]
I recommend only maintaining one supported current release. There should be no reason to attempt to backport this to v2.

**Comment by dsnz** [comment]
I was thinking about this too but surely there is old code with the api of version 2,0 (and older 1.0) and I don't have stats on the adoption/use of version 3.0
perhaps important fixes should make it to version 2.0 and improvements/features to version 3.0 only

**Comment by jsumners** [comment]
I consider you the primary maintainer of this module, now. So it's up to you how you want to support it. But my recommendation is to save yourself the trouble and only support one current major release. It is way too cumbersome to maintain two versions indefinitely.

You might consider adopting an "LTS" lifecycle. For example, a previous major release is only support for 6 months after a new major release. See https://www.fastify.io/docs/v2.14.x/LTS/ for an example.

**Comment by dsnz** [comment]
ok, it's decided
there will be no backport for this improvement
version 2.0 will get important fixes but big improvements/features will be for version 3.0 only (unless they are very easy to port to version 2.0 too)
