### ISSUE TITLE
Using pljson_table for nested JSON arrays

### ISSUE THREAD

**Issue by valisij** [pljson/pljson#189]
Hi all! I'm not sure that it is an issue, but I need some explanation for using `pljson_table`.
I'm trying to use pljson_table to JSON structure with nested arrays.
`SELECT *
  FROM TABLE(pljson_table.json_table(
              ' [[
                  {"date_b":"2020-03-01","date_e":null,"attribute":"GR","value":"704"},
                  {"date_b":"2020-03-01","date_e":null,"attribute":"TXT","value":"text1"}
                 ],
                 [
                  {"date_b":"2020-03-01","date_e":null,"attribute":"GR","value":"704"},
                  {"date_b":"2020-03-01","date_e":null,"attribute":"TXT","value":"text2"}
                 ]]',
              pljson_varray('[*].[*].date_b', '[*].[*].date_e'),
              pljson_varray('date_b', 'date_e'),
              table_mode => 'nested')
            );`
It causes an error "ORA-20120: column introduces more than one array, column# 1" on PLJSON_TABLE_IMPL, line 276. I understand that problem is in path (2nd argument). But I don't understand, how can I work with such structure. I read examples here, but there is no way to work with nested arrays.
Is it possible with PLJSON?

**Comment by dsnz** [comment]
Hi,

First of all we should say that there is no standard path syntax expression. The original pljson project introduced a simple path syntax which is a basic path language that any implementation is expected to have and is also appropriate for the size of this project.

For the implementation of pljson_table's nested mode a new syntax element was introduced,

```
[*]
```

for arrays. This syntax element is valid only within **pljson_table** and it has one practical limitation that each column must introduce one new array only. A subsequent column can go further nested introducing a new array etc. So, the first column must introduce only a single array.
In your case, the first column's path is

```
[*].[*].date_b
```
which introduces immediately 2 arrays and cannot be handled.

In fact what you want is equivalent to collapsing a 2 level structure into a single level structure and this is too much for nested mode.

If you alter a little your json input to the following

```
[
{ "arraynum":1, "data": [
 {"date_b":"2020-03-01","date_e":null,"attribute":"GR","value":"704"},
 {"date_b":"2020-03-01","date_e":null,"attribute":"TXT","value":"text1"}
] },
{ "arraynum":2, "data": [
 {"date_b":"2020-03-01","date_e":null,"attribute":"GR","value":"704"},
 {"date_b":"2020-03-01","date_e":null,"attribute":"TXT","value":"text2"}
] }
]
```

then you can get what you expect with the following code

```
select date_b, date_e from (
select * from table(pljson_table.json_table(
'[
{ "arraynum":1, "data": [
 {"date_b":"2020-03-01","date_e":null,"attribute":"GR","value":"704"},
 {"date_b":"2020-03-01","date_e":null,"attribute":"TXT","value":"text1"}
] },
{ "arraynum":2, "data": [
 {"date_b":"2020-03-01","date_e":null,"attribute":"GR","value":"704"},
 {"date_b":"2020-03-01","date_e":null,"attribute":"TXT","value":"text2"}
] }
]',
pljson_varray('[*].arraynum', '[*].data[*].date_b', '[*].data[*].date_e'),
pljson_varray('arraynum', 'date_b', 'date_e'),
table_mode => 'nested'
) )
);
```

In the next months I will try to speed up the implementation of pljson_table because it uses many internal Oracle collections which are slow and as a result it gets slow with complex nested json inputs. I will try to see if I can overcome this limitation but only if the speed does not suffer and the final code does not become unwieldy and incomprehensible (I repeat that nothing is promised).
