### ISSUE TITLE
ORA-31011: using pljson_util_pkg.sql_to_json( sql_query ), where an attribute containing an ampersand is selected 

### ISSUE THREAD

**Issue by rune139** [pljson/pljson#213]
Whenever you stick into "sql_query" some SQL that selects an attribute containing an ampersand ("&"-character) within its text string, the call to pljson_util_pkg.sql_to_json( "sql_query" ) fails with an XML-parsing error!

Here a sample query, that causes the error:

select  sql_query
, pljson_parser.get_version
, pljson_util_pkg.sql_to_json( sql_query ) 
from ( SELECT 'SELECT ''a''||'''||chr(38)||'''||''b'' from dual' sql_query from dual );

leads to:
ORA-31011: XML parsing failed
ORA-19202: Error occurred in XML processing
LPX-00241: entity reference is not well formed
Error at line 1
ORA-06512: at "SPED.PLJSON_UTIL_PKG", line 273
ORA-06512: at "SPED.PLJSON_UTIL_PKG", line 282
ORA-06512: at line 1
31011. 00000 -  "XML parsing failed"
*Cause:    XML parser returned an error while trying to parse the document.
*Action:   Check if the document to be parsed is valid.

This problem applies to PL/JSON v2.0.0 till latest version.

**Comment by dsnz** [comment]
Hi,

I examined the issue and it seems it has to do with an Oracle XSL processor bug.

It's strange but in order to produce JSON from sql, PLJSON first produces XML using Oracle XML features and this step goes fine without errors. Then a XSLT stylesheet converts this XML to JSON. It's this  step that fails when a ```&amp;``` is included in the text (your & is converted to ```&amp;``` as it should).

I have tried 3 different XSLT stylesheets (from entirely different sources) and there is still error. I also tried these stylesheets with a online converter and they produce a correct result (and of course the online converter did not crash). So, it seems it's an Oracle bug.

XSL is not my specialty (the opposite actually 😆 ) but I will try to research it more in the next week and post an update here.
I must say that you must not have high hopes of this being solved. I certainly will not file an Oracle bug again as Oracle does not resolve any bugs (it's well known that Oracle is interested for the cloud solution - or Tiktok 🤣 -  and not for the core database). Two bugs related to PLJSON have not been resolved in the last two years even though one is a serious performance bug and the other is a serious security issue. My effort will be mainly to verify the cause of this issue and perhaps find an acceptable workaround.

**Comment by dsnz** [comment]
P.S.
I did my tests and will do my research on 11g
if you can test with a newer database and report here it would be helpful

**Comment by rune139** [comment]
I testet with Oracle DB Version 19.0.0.0.0, but unfortunately with the same error:
this is the stack trace for the above query:

ORA-31011: XML parsing failed
ORA-06512: at "SPED.PLJSON_UTIL_PKG", line 273
ORA-19213: error occurred in XML processing at lines 1
LPX-00241: entity reference is not well formed
ORA-06512: at "SYS.XMLTYPE", line 138
ORA-06512: at "SPED.PLJSON_UTIL_PKG", line 240
ORA-06512: at "SPED.PLJSON_UTIL_PKG", line 282
ORA-06512: at line 1
31011. 00000 -  "XML parsing failed"
*Cause:    XML parser returned an error while trying to parse the document.
*Action:   Check if the document to be parsed is valid.

**Comment by boriborm** [comment]
XSLT transformation hasn't got "&" to "&amp;" transforming.
You can try add code before quote transforming

```<xsl:when test="contains($s,'&amp;')">
        <xsl:value-of select="substring-before($s,'&amp;')"/><![CDATA[&amp;]]><xsl:value-of select="substring-after( $s, '&amp;' )"/>   
      </xsl:when>
```
before line 192

must be like this:

```
<xsl:when test="contains($s,'&#xD;')">
        <xsl:call-template name="encode-string">
          <xsl:with-param name="s" select="concat(substring-before($s,'&#xD;'),'\r',substring-after($s,'&#xD;'))"/>
        </xsl:call-template>
      </xsl:when>
**<xsl:when test="contains($s,'&amp;')">
        <xsl:value-of select="substring-before($s,'&amp;')"/><![CDATA[&amp;]]><xsl:value-of select="substring-after( $s, '&amp;' )"/>   
      </xsl:when>**
      <xsl:otherwise><xsl:value-of select="$s"/></xsl:otherwise>
```

**Comment by rune139** [comment]
Thank you, 
on my PL/JSON v2.0.0 version the change was appx. line 136, but works well !

Pls. can you state here which version will have this change included?

I appreciate your quick and accurate help - thanks a lot.

**Comment by boriborm** [comment]
I installed package from master branch, added solution and tested your selection. Then wrote this solution in comments :)

**Comment by dsnz** [comment]
Hi all,
I didn't catch the discussion from start but
many thanks to Maxim for the nice workaround 👍 👏 

surely I can add this solution in both versions
but since the xsl stylesheet used is a tad old and has been updated I wonder if @boriborm
can help and tell us which of the following a bit newer xsl stylesheets to use

https://github.com/doekman/xml2json-xslt/blob/master/xml2json.xslt (an updated version of the xsl stylesheet by Doeke Zanstra currently used by PLJSON)

or

https://github.com/bramstein/xsltjson/blob/master/conf/xml-to-json.xsl (an alternate and good stylesheet)

or if the current one is adequate and stay with it (?)

and also where to install the workaround in the final chosen stylesheet

**Comment by rune139** [comment]
Well, now I tried all the special characters we eventually use with this query:

select  sql_query
, pljson_parser.get_version
, pljson_util_pkg.sql_to_json( sql_query ) 
from ( SELECT 'SELECT ''<>§$=?\a/|€@+*~#-_.,;äöüß''||'''||chr(38)||chr(39)||chr(39)||'''||''ÄÖÜ!"b'' from dual' sql_query from dual );

and I again got the parsing error when using the "<" less than character!
so I added, as suggested another when for this like:
      <xsl:when test="contains($s,'&lt;')">
        <xsl:value-of select="substring-before($s,'&lt;')"/><![CDATA[&lt;]]><xsl:value-of select="substring-after( $s, '&lt;' )"/>   
      </xsl:when>

sorry, don't know if there is a better way to do.
But astonishingly the ">" greater than character allready worked ... done in another section?

**Comment by boriborm** [comment]
Use &lt; and &gt; instead < and >

**Comment by rune139** [comment]
I did, but this input control on this website changed it to the <> characters..
e.g. I used:
<xsl:when test="contains($s,'&lt;')">
<xsl:value-of select="substring-before($s,'&lt;')"/><xsl:value-of select="substring-after( $s, '&lt;' )"/>
</xsl:when>

**Comment by dsnz** [comment]
I think @boriborm suggested just the following addition (from my source in preparation to update pljson)

```
      <!-- ambersand, addition by boriborm -->
      <xsl:when test="contains($s,'&amp;')">
        <xsl:value-of select="substring-before($s,'&amp;')"/><![CDATA[&amp;]]><xsl:value-of select="substring-after( $s, '&amp;' )"/>   
      </xsl:when>
      <!-- lt, addition by boriborm -->
      <xsl:when test="contains($s,'&lt;')">
        <xsl:value-of select="substring-before($s,'&lt;')"/><![CDATA[&lt;]]><xsl:value-of select="substring-after( $s, '&lt;' )"/>   
      </xsl:when>
```

@rune139 add exactly the above and try

**Comment by dsnz** [comment]
@rune139 
you haven't replied for long time

the workaround

```
<!-- ambersand, addition by boriborm -->
<xsl:when test="contains($s,'&amp;')">
  <xsl:value-of select="substring-before($s,'&amp;')"/><![CDATA[&amp;]]><xsl:value-of select="substring-after( $s, '&amp;' )"/>   
</xsl:when>
<!-- lt, addition by boriborm -->
<xsl:when test="contains($s,'&lt;')">
  <xsl:value-of select="substring-before($s,'&lt;')"/><![CDATA[&lt;]]><xsl:value-of select="substring-after( $s, '&lt;' )"/>   
</xsl:when>
```

works for the last test sql you provided (all special characters and some more) as I have tested
so if you don't report any other related problem within the next day I will close this issue and proceed with updating the versions

**Comment by rune139** [comment]
Sorry, but my latest input already wanted to tell you, that all my test cases worked fine with exactly these lines included.
pls. proceed with updating the versions.
Thanks a lot
