### ISSUE TITLE
Print tags with lower case

### ISSUE THREAD

**Issue by mzabala23** [pljson/pljson#219]
It's possible print tags with lower case, I use the next code

declare 
  ret pljson_list;
begin
  ret := pljson_util_pkg.sql_to_json('select  1 number_ef from dual');
  ret.print;
end;
/
but this print:

[{
  "NUMBER_EF" : 1
}]

I want print "number_ef" instead of "NUMBER_EF", that it's possible?

**Comment by boriborm** [comment]
Try ``select 1 "number_ef" from dual``

**Comment by mzabala23** [comment]
Hello @boriborm  thanks very much that is correct and work for me, I have other question, can I use pl/json for query with connect by prior and get nested json by levels?

Thanks very much for your help

**Comment by dsnz** [comment]
thank you @boriborm

@mzabala23 
since your issue has been solved, I must close it

for the second question regarding the "connect by" query, open a new issue with a nice **description** (an **algorithmic description**) and **example** of what you want to achieve because each person may understand it differently
