### ISSUE TITLE
Oracle 19c nonexistent LOB value For pljson_table.json_table

### ISSUE THREAD

**Issue by WoodG0b1in** [pljson/pljson#220]
Hello.
`select *
            from table(
              pljson_table.json_table(
                '{"items":[{"item":"EMPLOYEE_ID", "val":"1", "lbl":"", "typ":"", "tmpl":"", "vsl":1}]}',
                pljson_varray('items[*].item','items[*].val','items[*].lbl','items[*].typ','items[*].tmpl','items[*].vsl'),
                pljson_varray('item','val','lbl','typ','tmpl','vsl'),
                table_mode=>'nested'
              )
            )`

I get Ora-22922 on third request for this query. I try both version 3.4.1 and 2.5.2. On Oracle 11 I don't see this problem

**Comment by dsnz** [comment]
hi,
I'm on 11 and of course I don't get this error
unfortunately my 12 was damaged some time ago and I don't feel installing it again unless there is serious reason (because 2 databases on a small laptop is overkill)
your 19c is practically 12.2.0.3 and immediately I don't see any immediate difference that could possibly produce such an error **especially when no lob/clob operation is done inside pljson_table !**
the only clob used is the json text, so it has to do with Oracle converting the temporary clob of json text to permanent clob (automatically and messing lob locators in the process) and considering that
```ORA-22922 is a symptom of a program that is incorrectly handling LOB locators across transactions```
my first idea is that you do some commits/rollbacks between your queries
check carefully the sequence of operations you do if there is a commit/rollback intervening between the queries

if the above does not seem to help then please

1. try in both sqlplus and sqldeveloper and see if there is any difference
2. comment the exception section in ```pljson_table.ODCITableDescribe```, try again and post the full stack trace
3. try with a bind variable for the json text (you can do easily this in sqldeveloper with ```:json_text``` and when it prompts you for the bind value just paste the json text) and post what happens
4. do ```alter session set sql_trace=true;``` run the sql statement until it produces the error and then ```alter session set sql_trace=false;```, find the .trc file in your db trace directory (the correct trace file is best found such that the modified time is the time when you executed the last alter session command or use the 'Default Trace File' from ```select * from v$diag_info```) and post a link to this trace file so we can examine it

**Comment by WoodG0b1in** [comment]
Hello. I had
[json.zip](https://github.com/pljson/pljson/files/5331434/json.zip)

 collected trace

**Comment by dsnz** [comment]
Hi,

it's strange but your statement always passes thru this sequence before the error

```
PARSE
CLOSE
PARSE
EXEC
ERROR
```

ie. there is first a parse and immediate close without execution (!)
it seems to me that you run these statements via a JDBC client
also in your trace file a procedure ```write_to_clob()``` runs as well
and I wonder if it runs at end or along with each sql statement
tell us how this procedure is used

please

1. verify that you don't have any logon triggers (session, database, any!)
and if you have then post here the trigger code, remove them and continue with 2.

2. start a fresh ```sqlplus``` session and run
```
select *
from v$parameter
order by name
```
and post the result (first ```grant select any dictionary to <user>;``` as sysdba)

3. immediately following 2. run the following sequence exactly
```
alter session set events '10046 trace name context forever, level 28'

run your sql repeatedly (and nothing else) until you get error

alter session set events '10046 trace name context off'
```

3. tell us how many successful executions you had before the last one with the error
4. post the **.trc** file and also the **.out** file produced by tkprof for this .trc file
5. as sysdba run the following

```
exec dbms_feature_usage_internal.exec_db_usage_sampling(sysdate);

select u1.name,
       u1.detected_usages,
       u1.currently_used,
       u1.version
from   dba_feature_usage_statistics u1
where  u1.version = (select max(u2.version)
                     from   dba_feature_usage_statistics u2
                     where  u2.name = u1.name)
and    u1.detected_usages > 0
and    u1.dbid = (select dbid from v$database)
order by name;
```
