### ISSUE TITLE
4 byte Unicode chars

### ISSUE THREAD

**Issue by SergeyTenorio** [pljson/pljson#239]
Procedures pljson_printer.add_to_clob and flush_clob must use Length2 function like in pljson_parser.updateClob

**Comment by jsumners** [comment]
Seems there are defined ranges that denote the byte width to interpret based upon the first byte read -- https://en.wikipedia.org/wiki/UTF-8#Encoding

**Comment by dsnz** [comment]
Hi,

thank you for raising the issue

@SergeyTenorio &nbsp; can you please post also a short demo test of the issue (e.g. part of the code that made  you notice this) to better document this issue ?

I will have a look at it and do the correct fix this coming weekend as it's a strange season now and I am also working on a long due backport to v2 of many recent fixes in v3

(@jsumners &nbsp; it happens that Oracle handling of Unicode is full of mysteries; unfortunately clob operations need to know amount in 2-byte Unicode pieces - ! - so for a character that is 4 bytes the amount passed should be 2 not 1 and that's why length2 must be used)

**Comment by SergeyTenorio** [comment]
Hi, @dsnz 
here the sample code and result. 
[4byte_result.txt](https://github.com/pljson/pljson/files/5694863/4byte_result.txt)
[4byte.txt](https://github.com/pljson/pljson/files/5694864/4byte.txt)

We recently fixed this with dbms_lob.append, but ORA-22831 error sometimes occurs. 
So now we use length2.

**Comment by dsnz** [comment]
thank you
it will be fixed in the best way by next week

**Comment by dsnz** [comment]
@SergeyTenorio 

Hi,
Finally I have finished.
I have reviewed all code and made also some minor fixes beyond the fix for this issue (which had unfortunately been missed earlier).
The changes have been committed only in version v2 (master branch) at this time.
I noticed from your code sample that you must use an old and unsupported version (because you use the deprecated add_elem() function). I strongly suggest that you install version v2 which has minor incompatibilities and should work fine (add_elem() can be replaced with put()).

Unfortunately, I could not see an issue with your test before the changes. This is perhaps because only one character is 2 UTF-16 pieces long and the old code failed in certain combinations of 4-byte and 3/2-byte unicode chars. So, please run as much tests as you can and report if everything is okay (and post a more complicated test code if possible so that we have it as a good example).

**Comment by dsnz** [comment]
@SergeyTenorio 
will you be able to do testing on your site ?
