### ISSUE TITLE
PLJSON  types and packages not compiling .Need  urgent help , Please 

### ISSUE THREAD

**Issue by gkthomas65** [pljson/pljson#251]
We have upgraded our database from 12C to 19C and PLJSON packages and components became invalid.    I changed JSON_VALUE reference in the custom packages and other PLJSON packages to  schema .JSON_VALUE . As a result  many of PLJSON packages is valid and is good. However there are few type bodies and few packages are invalid and due to this reason , 
we have error in our application .  Can someone please help.  Appreciate very much .  Please advice what I need to do in order to get this work 

Following items are still invalid
types bodies
JSON
JSON_LIST
JSON_VALUE

Packages
JSON_DYN
JSON_EXT
JSON_HELPER
JSON_PARSER
George

**Comment by dsnz** [comment]
Hello,

from what you write it seems you have a very old version of PLJSON

you should download the latest release that is more compatible with your version (2.5.3) from

**[https://github.com/pljson/pljson/releases/download/v2.5.3/pljson-2.5.3.zip](https://github.com/pljson/pljson/releases/download/v2.5.3/pljson-2.5.3.zip)**

and install it cleanly

**don't** ever install at a schema named JSON_VALUE or any named the same as any old type/package name starting with **JSON_**

**after installation** your application may be working or not (we have created synonyms for old type/package names - see below - to new type/package names; but still this may not be enough depending on your exact version of 19c)
so, **you should change** in your code all type/package references from **JSON_<...>** to **PLJSON_<...>** so that your application does not depend on these synonyms (and even drop them manually) and then it will certainly work
(eg. JSON -> PLJSON, JSON_VALUE -> PLJSON_VALUE, etc.)

**Comment by gkthomas65** [comment]
> Hello,
> 
> from what you write it seems you have a very old version of PLJSON
> 
> you should download the latest release that is more compatible with your version (2.5.3) from
> 
> **https://github.com/pljson/pljson/releases/download/v2.5.3/pljson-2.5.3.zip**
> 
> and install it cleanly
> 
> **DON'T** ever install at a schema named JSON_VALUE or named the same as any old type/package name starting with **JSON_**
> 
> **after installation** your application may be working or not (we have created synonyms for old type/package names - see below - to new type/package names; but still this may not be enough depending on your exact version of 19c)
> so, **you should change** in your code all type/package references from **JSON_<...>** to **PLJSON_<...>** so that your application does not depend on these synonyms (and even drop them manually) and then it will certainly work
> (eg. JSON -> PLJSON, JSON_VALUE -> PLJSON_VALUE, etc.)

Thank you very much for the reply.   When we install. Can we install in the application schema  ? Will this overwrite the existing PLJSON objects.  Or do we need to manually uninstall all old objects and types.?
Thanks 
George

**Comment by dsnz** [comment]
Hi,

Yes you can and it's recommended to install in application schema.
Since, I don't know how old version you have, I suggest that

1. you use the **uninstall.sql** script of your **old version**
2. **check manually** that there are no objects with names starting with JSON (select from user_objects)
and also no synonyms starting with JSON (all_synonyms), and if you find any then drop it manually
3. happily install the new version with **new install.sql**

**Comment by gkthomas65** [comment]
from the master folder where can we find the current version of PLJSON? from  the server zip  we found  JSON_v1_0_4.zip
So I believe our current version is  PLJSON  1.0.4
In this case ,  Which new version is appropriate for us ..  Just wanted to double check before downloading 

Thanks for all help
George Thomas

    On Friday, March 19, 2021, 05:48:18 PM CDT, E.I.Sarmas ***@***.***> wrote:  
 
 


Hi,

Yes you can and it's recommended to install in application schema.
Since, I don't know how old version you have, I suggest that
   
   - you use the uninstall.sql script of your old version
   - check manually that there are no objects with names starting with JSON (select from user_objects)   
and also no synonyms starting with JSON (all_synonyms), and if you find any then drop it manually
   - happily install the new version with new install.sql

**Comment by dsnz** [comment]
Hi,

I repeat what I had said before

you should download the latest release that is more compatible with your version (2.5.3) from

https://github.com/pljson/pljson/releases/download/v2.5.3/pljson-2.5.3.zip

and install it cleanly  with the followin steps

- use the uninstall.sql script of your old version
- check manually that there are no objects with names starting with JSON (select from user_objects)
and also no synonyms starting with JSON (all_synonyms), and if you find any then drop it manually
- happily install the new version with new install.sql

DON'T ever install at a schema named JSON_VALUE or named the same as any old type/package name starting with JSON_

after installation your application may be working or not
we have created synonyms for old type/package names - see below - to new type/package names; but still this may not be enough depending on your exact version of 19c
so, **you must change in your code all type/package references from JSON_<...> to PLJSON_<...> (eg. JSON -> PLJSON, JSON_VALUE -> PLJSON_VALUE, etc.)** so that your application does not depend on these synonyms (and even better drop them manually) and then your application will certainly work

**Comment by jsumners** [comment]
The releases page lists all available versions -- https://github.com/pljson/pljson/releases

**Comment by gkthomas65** [comment]
Thank you so much
George 
    On Monday, April 5, 2021, 10:33:07 AM CDT, E.I.Sarmas ***@***.***> wrote:  
 
 


Hi,

I repeat what I had said before

you should download the latest release that is more compatible with your version (2.5.3) from

https://github.com/pljson/pljson/releases/download/v2.5.3/pljson-2.5.3.zip

and install it cleanly with the followin steps
   
   - use the uninstall.sql script of your old version
   - check manually that there are no objects with names starting with JSON (select from user_objects)   
and also no synonyms starting with JSON (all_synonyms), and if you find any then drop it manually
   - happily install the new version with new install.sql

DON'T ever install at a schema named JSON_VALUE or named the same as any old type/package name starting with JSON_

after installation your application may be working or not
we have created synonyms for old type/package names - see below - to new type/package names; but still this may not be enough depending on your exact version of 19c
so, you must change in your code all type/package references from JSON_<...> to PLJSON_<...> (eg. JSON -> PLJSON, JSON_VALUE -> PLJSON_VALUE, etc.) so that your application does not depend on these synonyms (and even better drop them manually) and then your application will certainly work
