### ISSUE TITLE
Using empty_clob() before dbms_lob.createtemporary()

### ISSUE THREAD

**Issue by xukapy** [pljson/pljson#268]
I stumbled across an questionable construction  looking through  the source code and examples:

`
 my_clob := empty_clob();
 dbms_lob.createtemporary(my_clob, true);
`

What's the point of the first operation? Is it necessarily to make the first initialization before calling   dbms_lob.createtemporary?

**Comment by dsnz** [comment]
Hi,

where exactly did you see this ?

**Comment by dsnz** [comment]
Hi,

I searched the code and found a few instances of the pair you said.
In ex11, pljson_value and pljson_parser.
This is carried over from old code (!) :D 
You are correct that is questionable because the first statement is unnecessary.
Again perhaps this is due to old code maintenance that sometime added a createtemporary call after the empty_clob.
It is harmless but perhaps should be removed so as not to raise such questions.
I'll keep a note in future updates to clean these up.

**Comment by xukapy** [comment]
Thank you for a prompt response.
