### ISSUE TITLE
API overhaul

### ISSUE THREAD

**Issue by jsumners** [pljson/pljson#28]
With Oracle 12 having a native "JSON" type, I think it would be good to look at how this project can be overhauled. PL/JSON supports far more than Oracle's native type, but the two conflict due to naming. So at the very least it would be nice to re-write PL/JSON's internals, and exposed API, to not conflict with Oracle's native type. For backward compatibility, a shim API should be provided that people on versions less than 12 can optionally install and use.

**Comment by Nerd89** [comment]
Hallo,
Has the next Version of pljson a complete 12c Support, so it use the native types/functions? 
if so, is there any releasedate?

**Comment by jsumners** [comment]
@Nerd89 short answer: no.

I don't really have access to a 12c database to develop against; nor really even the time. So this bug is here for those who have a pressing need and want to tackle it.

**Comment by dsnz** [comment]
I am sure I had left a comment with a proposal here which somehow disappeared !
Anyway I repeat. I am proposing (and will implement in the near future) a renaming of the types PL/JSON uses, so to start with pljson_ instead of json_ and the creation of synonyms with json_ prefix. In 12c these synonyms will fail but the pljson_ names will exist. In older databases both names will be available and so there will be compatibility with existing applications that used old naming. New 12c applications should use the pljson_ prefix. I introduced this logic in the recent feature pljson_table() which provides similar functionality to 12c json_table().
If there is any other idea, I would be glad to hear.

**Comment by jsumners** [comment]
@dsnz I certainly didn't remove it. Maybe the post never completed? Anyway, that seems like a very acceptable patch to get things working in 12c.

**Comment by dsnz** [comment]
@jsumners

Surely I messed something since I usually work on many tabs/windows at the same time.
In my original post I had indicated that I would develop json_table() functionality which I have completed.

I also intend to implement 12c compatibility and installation/testsuite setup to be complete and working perfectly with 10g, 11g, 12c.

In the future I may perhaps produce a tutorial/doc manual in README which will include most examples and contents from http://docs.tpu.ru/docs/oracle/plsql_json/v104/doc.pdf and http://database-geek.com/2009/03/25/json-in-and-out-of-oracle-json-data-type/ (there was also another good README in the past but I can't locate it anymore).
I think this is missed a lot by many users (or prospective users) of the library.

**Comment by jsumners** [comment]
Awesome. I can't say enough how much I appreciate all of your contributions.

You are correct. Our documentation is severely lacking. I noticed the same thing after discovering the project and wrote my own post -- https://jrfom.com/2015archive/2011/01/26/pljson-library/index.html . It seems it was good enough for @jkrogsboell to link it for a few answers on the old sf.net forum :)

**Comment by Nerd89** [comment]
I test currently supporting at 12c. I renamed all packages with a prefix "lib_".
The test is good until now, no errors.

**Comment by dsnz** [comment]
Actually you need not rename anything. It installs as is flawlessly in 12c and works flawlessly too ! I was about to report this after having finished some tests. The 'JSON' word and others are not reserved contrary to popular belief. I will have more details  in a few days.

**Comment by Nerd89** [comment]
I read, that Oracle will "do something more" with JSON, so it's better when it has a prefix. 
Next test is with extended data type

**Comment by jsumners** [comment]
I agree. We should avoid the potential naming collision. It's not like Oracle is going to concede to us.

**Comment by dsnz** [comment]
ok, i will go with renaming
