### ISSUE TITLE
Problem when using cursor in oracle

### ISSUE THREAD

**Issue by andcmatias** [pljson/pljson#291]
I'm creating a select with several cursors inside

When there is only one return, it inserts the tag name and inside another tag with the same name followed by _ROW

Example:

set serveroutput on size 10000;
set define off;
DECLARE
   STRING                              VARCHAR2(4000);
   RETORNO                             CLOB := TO_CLOB(' ');
   V_JSON_LIST                         JSON_LIST;
BEGIN
   STRING := 'SELECT 1 "id", ' ||
             '       ''name'' "text", ' ||
             '       CURSOR ( ' ||
             '          SELECT 1 "id", ' ||
             '                 ''name'' "text" ' ||
             '          FROM DUAL ' ||
             '       ) "group1", ' ||
             '       CURSOR ( ' ||
             '         SELECT 1 "id", ' ||
             '                ''name'' "text", ' ||
             '                CURSOR( ' ||
             '                   SELECT 1 "id", ' ||
             '                          ''name'' "text" ' ||
             '                   FROM   DUAL ' ||
             '                   UNION ALL ' ||
             '                   SELECT 2 "id", ' ||
             '                          ''name'' "text" ' ||
             '                   FROM   DUAL ' ||
             '                ) "group2_1" ' ||
             '         FROM   DUAL ' ||
             '       ) "group2" ' ||
             'FROM   DUAL ';
   V_JSON_LIST := JSON_UTIL_PKG.SQL_TO_JSON(STRING);
   PLJSON_PRINTER.PRETTY_PRINT_LIST(V_JSON_LIST, FALSE, RETORNO, 0, FALSE);
   DBMS_OUTPUT.PUT_LINE(RETORNO);
END;

Return:
[{"id":1,"text":"name","group1":{"group1_ROW":{"id":1,"text":"name"}},"group2":{"group2_ROW":{"id":1,"text":"name","group2_1":[{"id":1,"text":"name"},{"id":2,"text":"name"}]}}}]

Note that the group2_1 tag has 2 returns and returns correctly.

**Comment by dsnz** [comment]
Hi,

this package uses internally Oracle's **dbms_xmlgen** which produces an xml with the names you see

for the final output we use a xml stylesheet to transform the produced xml to json

in some sense the final result is logical
your **group1** for example does not contain an array but a single object so it has to be named  
(while objects in arrays are nameless !)

you can try to change the code and make **group1** be a union all returning more than one rows and
then you will see that the _ROW key will disappear

what you can do:

- change the stylesheet to be very smart to avoid outputting the extra _ROW object (and kindly make a PR as well :) ) cause I know very little about stylesheets and I am not even sure if this is possible
- use the example below with which you have freedom to name the inner _ROW keys as you like (in my example I used _ROW again but obviously you can change it as you like)
the example uses Oracle **objects** instead of **cursors** and seems complicated since some **types** have to be predefined
but again is the only solution at your control

```
create or replace type group1_row is object (id number, text varchar2(100));
create or replace type t_group1 is table of group1_row;
create or replace type group2_row is object (id number, text varchar2(100), group1_rows t_group1);
create or replace type t_group2 is table of group2_row;

DECLARE
  STRING VARCHAR2(4000);
  RETORNO CLOB := TO_CLOB(' ');
  V_JSON_LIST PLJSON_LIST;
BEGIN
  STRING := q'[SELECT 1 "id", 'name' "text",
  cast(multiset( SELECT 1, 'name' FROM DUAL ) as t_group1) "group1",
  cast(multiset( SELECT 1, 'name',
    cast(multiset( select * from (SELECT 1, 'name' FROM DUAL UNION ALL SELECT 2, 'name' FROM DUAL )) as t_group1) "group2_1" FROM DUAL ) as t_group2) "group2"
  FROM DUAL
  ]';
  --dbms_output.put_line(string);
  V_JSON_LIST := PLJSON_UTIL_PKG.SQL_TO_JSON(STRING);
  PLJSON_PRINTER.PRETTY_PRINT_LIST(V_JSON_LIST, FALSE, RETORNO, 0, FALSE);
  DBMS_OUTPUT.PUT_LINE(RETORNO);
END;
```

**Comment by andcmatias** [comment]
Thank you for your help.

But I managed to solve it by changing the pljson_util_pkg.package.sql file

I changed line 239 after 

I modified
<xsl:template match="*[count(../*[name(../*)=name(.)])=count(../*) and count(../*)&gt;1] ">
for
<xsl:template match="*[not(self::ROWSET) and count(../*[name(../*)=name(.)])=count(../*) and count(. ./*)&gt;0]">

and on line 328
I commented the block
  if(l_num_rows > 1) then
    return pljson_list(pljson(l_returnvalue).get('ROWSET'));
  end if;

  declare ret pljson_list := pljson_list();
  begin
    ret.append(
      pljson(
        pljson(l_returnvalue).get('ROWSET')
      ).get('ROW')
    );
    return ret;
  end;

leaving
return pljson_list(pljson(l_returnvalue).get('ROWSET'));

I don't know if it's right, but it worked for me.

**Comment by dsnz** [comment]
Hi,

your changes are not probably right

it may be appear correct only because of the stylesheet change

the line numbers you specify are not correct and probably refer to an older version
(and also you use json_util_pkg in your code which is another sign of an older version);
**only v3 in branch develop_v3 is support**ed

the code block you removed should stay there :)

I advise that you test with many many scenarios rather than the one only you posted
(and if you manage to make a better stylesheet, please make a PR but at branch develop_v3 :) ) 

anyway I am closing this thread now
