### ISSUE TITLE
Parsing is slow.

### ISSUE THREAD

**Issue by libliflin** [pljson/pljson#61]
Hi,

I tried to parse 6kb of json and it took a half second. Is this normal?

**Comment by jsumners** [comment]
Are you saying it took 500ms to parse a fairly large amount of text? That doesn't sound too slow to me, considering the language. PL/SQL is not a performant language[1]. We have to parse through the JSON character by character to build the PL/SQL objects.

You could try upping the optimization level -- https://github.com/pljson/pljson/blob/master/install.sql#L8

[1] -- http://www.oracle.com/technetwork/articles/sql/11g-plsql-091775.html

**Comment by libliflin** [comment]
Hi, 

I found some time during lunch and was able to create a small test case.

String of length 7135.

On my machine... (Windows; Oracle XE)
firefox developer console: 74ms for 1000 passes https://gist.github.com/libliflin/a123299819d76208c1de43da26565327
pljson: 244ms in one pass https://gist.github.com/libliflin/ea90fdf001124d5e4fe0715ad5ce64a5

So... 3,300x slower? roughly?

**Comment by jsumners** [comment]
Initially, ~240ms. Subsequent invocations are around ~100ms due to Oracle using the cached compiled procedure. In other words, a significant portion of that initial duration is Oracle compiling the procedure.

I don't think you can compare the parsing in Firefox/Safari/Chrome/Edge to PL/JSON. The underlying technologies are vastly different. In the browsers the JSON is being parsed by a very optimized native JavaScript engine. Whereas PL/SQL is simply doing the best it can with the language and engine that is available.

Can PL/SQL be faster? I'm sure it can. If you are willing to dig in and come up with some optimizations we would sure love to see them in a pull request.

If you're using Oracle 12c (12.1) then there is some limited JSON support natively available. I don't seem to have it in the database I have access to, but you may want to give it a try: `json_value(l_t, '$.taglib')`.

**Comment by dsnz** [comment]
will be improved, issue #62

**Comment by dsnz** [comment]
finally this issue is separate from #62 (though #62 improves a bit parsing)
the discussion about parsing improvements has been moved to #105
