### ISSUE TITLE
Implement tests using utPLSQL and configure CI

### ISSUE THREAD

**Issue by Pazus** [pljson/pljson#87]
Hi.

I've bean using pljson in production for about 3 years on 10-11g, so thank you for the great product!

As an author of utPLSQL testing framework let me propose you to migrate your tests to utPLSQL, documentation, examples etс are available here:
https://github.com/utPLSQL/utPLSQL/blob/master/docs/index.md
https://github.com/utPLSQL/utPLSQL-demo-project

Also you can see how we have established a CI infrastructure to test our builds using Travis CI.

If you have any qustions - feel free to contact me!

**Comment by dsnz** [comment]
Hello,

It's good to hear that a testing framework for PL/SQL is alive and well. When pljson started the original authors implemented a custom testing framework which has worked well until now, though a bit inconsistent sometimes. Be sure that in any following update of pljson we will strongly consider to use the utPLSQL framework (or at least incorporate it wholly or partly along with our custom framework) since all changes and new features are always unit tested.

**Comment by jsumners** [comment]
@Pazus this is definitely interesting. I would certainly like to see a PR against the develop branch.

**Comment by jgebal** [comment]
@jsumners PR created ;)

**Comment by Pazus** [comment]
Hi all. We have published the docker scripts we use to build dockers for our Travis CI.
https://github.com/utPLSQL/docker-scripts
