### ISSUE TITLE
using json_list in example from ex_pljson_table

### ISSUE THREAD

**Issue by yanko** [pljson/pljson#95]
is there a way to use the below json structure to turn it into a table()? {tx}
`[{
  "id" : 0,
  "displayname" : "Receiving",
  "qty" : 5
}, {
  "id" : 2,
  "displayname" : "Front",
  "qty" : 4
}]`

`select *
  from table(pljson_table.json_list_table('[{
  "id" : 0,
  "displayname" : "Receiving",
  "qty" : 5
}, {
  "id" : 2,
  "displayname" : "Front",
  "qty" : 4
}]',
                                      pljson_varray('id',
                                                    'displayname',
                                                    'qty'),
                                      pljson_varray('id',
                                                    'displayname',
                                                    'qty')));`

**Comment by dsnz** [comment]
Hi,

If I understand well you ask for a new procedure **json_list_table()** within pljson_table that will be able to unpivot a list into a table !
I like to receive such requests because this is feedback that pljson is used extremely :)

Well, I think it can be done and certainly I will put this first into the list of things to do (and I was about to start the updating documentation which is very old and minimal ...). Of course there will be some limitations which I cannot think of at this moment. How many objects do you expect to be within each list, and how many elements within each object ?

Until I start this development, I suggest a workaround with dynamic sql which can be sped up a lot depending on the details of your application.

```
create table id_qty_tab(
  id number(6,0) not null,
  qty number(6,0) not null
);

declare
  id1 number;
  qty1 number;
begin
  for i in 1..2 loop
    execute immediate
    'select * from table(pljson_table.json_table(
    ''{ l: [
         { "id" : 0, "displayname" : "Receiving", "qty" : 5 },
         { "id" : 2, "displayname" : "Front", "qty" : 4 }
       ]
    }'',
    pljson_varray(''l['||i||'].id'', ''l['||i||'].qty''),
    pljson_varray(''id'', ''qty'')
    ))' into id1, qty1;
    insert into id_qty_tab values(id1, qty1);
  end loop;
end;
```

**Comment by yanko** [comment]
Hello,

Yes exactly that, so I wouldn't need to insert it into a table as the work around. 

At the moment I don't foresee more than 3 elements within each object
and for me I would have just one list with 13 objects, since the needed functionality has only 13 different locations.
so it should not be that heavy. altho the column in the table that will have this structure has over 1M records... but that is another story..

I am using pljson in oracle xe when I make web service calls from db. trying to move away from soap web services.
Btw, thank you very much for keeping the pljson going. Would be cool to find out how much it actually is used out there.

**Comment by dsnz** [comment]
Hi,
I will surely implement this as it is very interesting indeed !
But since I cannot tell you when it will be ready, I propose you try the workaround I posted before.
It is a very inefficient workaround but with just 13 objects in a list and with just 3 elements in each object it will be fast with today's processors. It would be good also to time this workaround and inform me about the size in bytes if the json input and how much time it takes (just for reference comparison).

**Comment by yanko** [comment]
Hi,
we are using a different work around but when I get a chance I will compare both and use the one that has best results and will share it here. looking forward the implementation.
tx.

**Comment by yanko** [comment]
where can I find out anynews about this?

**Comment by jsumners** [comment]
This issue would be updated with any information regarding an implementation.

**Comment by dsnz** [comment]
Hi,
There is already work done on this but not finished yet.
As it is vacation period now and there are some other pressing stuff to do in the first 3-4 weeks of September, I dare say that a first working implementation will be committed in the first 2 weeks of October (and it is possible a surprise of an earlier time depending on the circumstances).
To summarize, I will try to deliver until October 15 the latest, if all goes well.
I hope this is okay with you.

**Comment by KingsGithub** [comment]
If you are using Oracle version 12.2.xx then it is far better to use the built-in json functionality since it allows one to deal directly with columns and tables without having any need for work-arounds or the use of the pljson package. From 12.2 there is no point in using that package anymore. 

===>>> BUT  <<<===  a great deal of thanks to DSNZ and all those who created and maintained it because I still need it for Oracle 12.1.

I believe that if you have the APEX 5 package available in your database prior to  version 12.2 you can also make use of the json functions/procedures in that package.

**Comment by yanko** [comment]
Thank you @KingsGithub unfortunately I am stuck with 11.2(no APEX) and indeed thank you @dsnz and others for pljson!

**Comment by dsnz** [comment]
@KingsGithub thanks for your thanks, we don't compete with Oracle obviously but pljson has strong history and is easy to use and equally capable for practical applications
as you will see the latest addition will be much less verbose and easier to use than the 12.2 equivalent nested columns in json_table
also if you have come across features/capabilities not covered well with 12.2 we would like to know for possible implementation within pljson

@yanko what you asked is almost ready,
I want to test it a bit more though and I wonder if you could post some big, realistic and complex examples of what you want to do (with complex I mean, many columns but not within same list all, instead many nested in objects within the main list and even many levels deep)
if the data is sensitive then you can email to me directly

**Comment by dsnz** [comment]
the enhancement has been implemented in latest commit

**Comment by yanko** [comment]
Thank you @dsnz 

as far as data goes, the column will not have more than 15 object in the array with 3 attribute in each object. the table that will hold this column will have over 1M records. but we will first fetch the record we need and then run your function to parse the json in the column. 
so it should not be heavy at all.

I don't have the data yet, since we are still developing.
if you need help testing I could write few cases that would resemble what we would use it for and post it here..?

thank you again.

**Comment by dsnz** [comment]
well I have released already the code,
I expect that after you run it, you post here your comments/bug reports along with some real test cases (anonymized perhaps)

**Comment by dsnz** [comment]
well I have already released the code (see last 3 examples in ex_pljson_table.sql on how to use)

I expect that after you run it, you post here your comments/bug reports along with some real test cases (perhaps anonymized)

**Comment by whitfordtech** [comment]
Hi, I'm very interested in this feature but cant seem to figure how to use it to navigate through an array of JSON structures and convert to a table. The examples I'm finding dont show arrays of data and I cant get it to work. 

trying to do this ...

```
select *
from table(
pljson_table.json_table(
'{"data":
  [{
   "name": "name 3",
   "description": "blah blah...",
   "type": "text",
   "created_time": "2015-12-21T19:23:29+0000",

  },
  {
   "name": "name 3",
   "description": "blah blah...",
   "type": "text",
   "created_time": "2015-12-21T19:23:29+0000",
   },
   ...
   ...
   }]
}',
pljson_varray('data.name', 'data.extra', 'data.age', 'data.shares.count', 'data.missing'),
pljson_varray('name', 'extra', 'map', 'count', 'whatelse'))
)
```

Appreciate your help.

**Comment by dsnz** [comment]
Hello,

your example does not work because you copied verbatim the wrong example and you replaced only the json text but not some extra information that is needed to work
(also the json text is not valid json !)

here is a revision of your select with some modifications I made that work
the modifications are mainly in the last 3 lines (which I have highlighted),
and you should change the first 2 of them to your liking

select *
from table(
pljson_table.json_table(
'{"data":
  [{
   "name": "name 1",
   "description": "blah blah... 1",
   "type": "text 1",
   "created_time": "2015-12-21T19:23:29+0000"
  },
  {
   "name": "name 2",
   "description": "blah blah... 2",
   "type": "text 2",
   "created_time": "2015-12-21T19:23:29+0000"
  }]
}',
**pljson_varray('data[\*].name', 'data[\*].type'),**
**pljson_varray('name', 'type'),**
**table_mode => 'nested'**
))

**Comment by whitfordtech** [comment]
Thanks for the amazingly quick response!!

Unfortunately I get the following error when running the above: 

ORA-06553: PLS-306: wrong number or types of arguments in call to 'JSON_TABLE'

suggesting I might have the wrong version of json_table as it doesn't recognize the table_mode parameter. When I look at json_table_impl.typ it doesn't seem to have a prototype to support this parameter.  I got the source from src/addons. 

I have also searched the repository for the term 'table_mode' and it doesnt find anything - what am I doing wrong?

**Comment by dsnz** [comment]
have you downloaded the latest development branch ?
(the master branch is not updated and will soon be replaced by the development branch)

**Comment by whitfordtech** [comment]
Please excuse my ignorance I am new to Github - where can I find the development branch?

**Comment by whitfordtech** [comment]
Ignore that - have found my way! Thanks again!

**Comment by dsnz** [comment]
okay, thank you too and feel free to ask any other question
