### ISSUE TITLE
some updates

### ISSUE THREAD

**Issue by boGitt** [pljson/pljson#97]
json
--add "getJsonObject" and "getJsonArray"  and "getString"
[src.zip](https://github.com/pljson/pljson/files/1161606/src.zip)

**Comment by jsumners** [comment]
I might have a different opinion of the changes, I can't comment on the code because I am unable to review it. There would be too much work involved in 1) downloading and extracting the zip, 2) figuring out which source branch it is written against, and 3) creating a difference to determine the changes.

I sincerely thank you for trying to contribute to the project. But I must ask that contributions be submitted as pull requests. For a basic introduction to using Git and GitHub for collaboration, please read https://jrfom.com/posts/2017/03/08/a-primer-on-contributing-to-projects-with-git/

Feel free to re-open this issue as a pull request.

**Comment by boGitt** [comment]
Sorry for my way to submit codes, I just want provide some advices and don't want change the codes.Whether accept or not it's determined by the owners.It may be helpful for the users to get deep nodes without to many transmit.In fact,i want add a method for "json_list" to return a type of "json",but I found it can't supported. Lastly,the codes and technique all the members of group is so skilled .

**Comment by jsumners** [comment]
Please don't feel intimidated to submit code. We will provide guidance to get it up to par so that it can be incorporated. Even if you don't want the code incorporated, using a pull request to show what you are suggesting is the best course of action. It lets us see the code right here on GitHub so that we can review it mare easily.

**Comment by boGitt** [comment]
Thanks,i will do my better.
Are't you sleeping?Is that night over there?

**Comment by jsumners** [comment]
Yes, it was late.
